# Generated by Django 3.0.4 on 2020-03-30 07:02

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # CREATE TABLE "permissions" ("id" serial NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL,
        # "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "title"
        # varchar(100) NOT NULL UNIQUE);
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'permissions',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
